// Auto-generated by talker_rust_logger
use crate::frb_generated::StreamSink;

// --- Data Structures (Generated locally for FRB) ---

#[derive(Clone, Debug)]
pub enum LogLevel {
    Trace,
    Debug,
    Info,
    Warn,
    Error,
}

#[derive(Clone, Debug)]
pub struct LogEntry {
    pub time_millis: i64,
    pub level: LogLevel,
    pub tag: String,
    pub msg: String,
}

// --- Converters ---

impl From<talker_rust_logger::LogLevel> for LogLevel {
    fn from(l: talker_rust_logger::LogLevel) -> Self {
        match l {
            talker_rust_logger::LogLevel::Trace => LogLevel::Trace,
            talker_rust_logger::LogLevel::Debug => LogLevel::Debug,
            talker_rust_logger::LogLevel::Info => LogLevel::Info,
            talker_rust_logger::LogLevel::Warn => LogLevel::Warn,
            talker_rust_logger::LogLevel::Error => LogLevel::Error,
        }
    }
}

impl From<talker_rust_logger::LogEntry> for LogEntry {
    fn from(e: talker_rust_logger::LogEntry) -> Self {
        Self {
            time_millis: e.time_millis,
            level: e.level.into(),
            tag: e.tag,
            msg: e.msg,
        }
    }
}

// --- Log Stream Entry Point ---

pub fn create_log_stream(sink: StreamSink<LogEntry>) {
    let sink = sink.clone();
    // Register the callback with the library.
    // This connects the library's logger to the FRB stream.
    // NOTE: This initializes the logger to ONLY send logs to Talker (Dart).
    // If you want native platform logs (Logcat/Console) as well, use `init_with_logger` 
    // and pass your platform logger implementation.
    let _ = talker_rust_logger::init(move |entry| {
        let _ = sink.add(entry.into());
    });
}
