// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Analyze an audio file and return a list of note events.
Future<List<NoteEvent>> analyzeAudioFile({required String path}) =>
    RustLib.instance.api.crateApiPitchAnalyzeAudioFile(path: path);

/// Detect pitch from a real-time audio buffer.
Future<LivePitch> detectPitchLive({
  required List<double> samples,
  required double sampleRate,
}) => RustLib.instance.api.crateApiPitchDetectPitchLive(
  samples: samples,
  sampleRate: sampleRate,
);

class LivePitch {
  final double hz;
  final int midiNote;
  final double clarity;

  const LivePitch({
    required this.hz,
    required this.midiNote,
    required this.clarity,
  });

  @override
  int get hashCode => hz.hashCode ^ midiNote.hashCode ^ clarity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LivePitch &&
          runtimeType == other.runtimeType &&
          hz == other.hz &&
          midiNote == other.midiNote &&
          clarity == other.clarity;
}

class NoteEvent {
  final double startTime;
  final double duration;
  final int midiNote;

  const NoteEvent({
    required this.startTime,
    required this.duration,
    required this.midiNote,
  });

  @override
  int get hashCode =>
      startTime.hashCode ^ duration.hashCode ^ midiNote.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteEvent &&
          runtimeType == other.runtimeType &&
          startTime == other.startTime &&
          duration == other.duration &&
          midiNote == other.midiNote;
}
